# Runtime OIDC config injection.
#
# At container start, write a small /config.js that the served index.html
# loads BEFORE the React bundle. The bundle reads `window.POGLY_RUNTIME_CONFIG`
# in src/Auth/oidc.ts and prefers those values over anything baked at build
# time. If OIDC env vars are unset, an empty config is written and the React
# app falls back to Mode 1 (anonymous tokens).
#
# This approach (vs sed-rewriting the bundle in place) avoids accidentally
# clobbering identical-looking string literals elsewhere in the JS.
#
# Note: this runs once per container start. Changing the env vars requires
# `docker run` again (re-creating the container from the image), not
# `docker start` of an existing one.
inject_runtime_config() {
  local issuer="${OIDC_ISSUER:-}"
  local client_id="${OIDC_CLIENT_ID:-}"

  # JSON-string-escape for safe inclusion in a JS string literal. Handles
  # backslashes and double quotes; URLs and client IDs shouldn't contain
  # control chars but escape defensively.
  json_escape() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
  }

  cat > /usr/share/caddy/config.js <<EOF
// Generated by docker/entrypoint.sh at container start.
window.POGLY_RUNTIME_CONFIG = {
  OIDC_ISSUER: "$(json_escape "$issuer")",
  OIDC_CLIENT_ID: "$(json_escape "$client_id")"
};
EOF

  if [ -n "$issuer" ] && [ -n "$client_id" ]; then
    echo "Runtime config: OIDC enabled (issuer=$issuer, client_id=$client_id)"
  else
    echo "Runtime config: OIDC disabled (anonymous-token mode)"
  fi
}

inject_runtime_config

deploy() {
  # Wait for the spacetime HTTP port to start accepting connections.
  # Uses bash's built-in /dev/tcp probe so we don't depend on curl, on the
  # `spacetime` CLI knowing about a `local` server alias, or on any specific
  # response payload.
  until (echo > /dev/tcp/127.0.0.1/3000) 2>/dev/null
  do
    echo "Waiting for server to start..."
    sleep 1
  done
  echo "Server is up; publishing modules."

  read -ra module_names <<<"$MODULES"
  echo "Publishing ${#module_names[@]} modules"
  for module in "${module_names[@]}"
  do
    echo "$module"
    spacetime publish --bin-path /app/pogly.wasm --server http://localhost:3000 --anonymous --yes "$module"
  done
}

# Kill all parallel processes below
trap "kill 0" SIGINT

caddy run --config /etc/caddy/Caddyfile --adapter caddyfile \
& spacetime start --listen-addr 0.0.0.0:3000 --data-dir /stdb \
& deploy \
&& wait