# Runtime OIDC config injection.
#
# At container start, write a small /config.js that the served index.html
# loads BEFORE the React bundle. The bundle reads `window.POGLY_RUNTIME_CONFIG`
# in src/Auth/oidc.ts and prefers those values over anything baked at build
# time. If OIDC env vars are unset, an empty config is written and the React
# app falls back to Mode 1 (anonymous tokens).
#
# This approach (vs sed-rewriting the bundle in place) avoids accidentally
# clobbering identical-looking string literals elsewhere in the JS.
#
# Note: this runs once per container start. Changing the env vars requires
# `docker run` again (re-creating the container from the image), not
# `docker start` of an existing one.
inject_runtime_config() {
  local issuer="${OIDC_ISSUER:-}"
  local client_id="${OIDC_CLIENT_ID:-}"

  # JSON-string-escape for safe inclusion in a JS string literal. Handles
  # backslashes and double quotes; URLs and client IDs shouldn't contain
  # control chars but escape defensively.
  json_escape() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
  }

  cat > /usr/share/caddy/config.js <<EOF
// Generated by docker/entrypoint.sh at container start.
window.POGLY_RUNTIME_CONFIG = {
  OIDC_ISSUER: "$(json_escape "$issuer")",
  OIDC_CLIENT_ID: "$(json_escape "$client_id")"
};
EOF

  if [ -n "$issuer" ] && [ -n "$client_id" ]; then
    echo "Runtime config: OIDC enabled (issuer=$issuer, client_id=$client_id)"
  else
    echo "Runtime config: OIDC disabled (anonymous-token mode)"
  fi
}

inject_runtime_config

deploy() {
  # Wait for the spacetime HTTP port to start accepting connections.
  # Uses bash's built-in /dev/tcp probe so we don't depend on curl, on the
  # `spacetime` CLI knowing about a `local` server alias, or on any specific
  # response payload.
  until (echo > /dev/tcp/127.0.0.1/3000) 2>/dev/null
  do
    echo "Waiting for server to start..."
    sleep 1
  done
  echo "Server is up."

  # We publish each module at most once per persistent /stdb volume. The wasm
  # itself only changes when the image is rebuilt; re-publishing on every
  # restart would either churn unnecessarily (anonymous identity changes) or
  # fail (the new anonymous identity isn't the wasm owner anymore). A sentinel
  # file inside /stdb tracks the "already published" state and survives
  # restarts because /stdb is a docker volume.
  #
  # To force a republish (e.g. after updating to a new image with a new wasm),
  # either delete the sentinel before restarting:
  #     docker exec <container> rm /stdb/.pogly-published-<module>
  # or set POGLY_FORCE_REPUBLISH=1 in the environment.
  read -ra module_names <<<"$MODULES"
  for module in "${module_names[@]}"
  do
    sentinel="/stdb/.pogly-published-$module"
    if [ -f "$sentinel" ] && [ "${POGLY_FORCE_REPUBLISH:-}" != "1" ]; then
      echo "Module '$module' already published (sentinel $sentinel present) - skipping."
      continue
    fi

    echo "Publishing module '$module'..."
    if spacetime publish --bin-path /app/pogly.wasm --server http://localhost:3000 --anonymous --yes "$module"; then
      touch "$sentinel"
      echo "Module '$module' published successfully."
    else
      echo "Failed to publish '$module' - sentinel not written, will retry on next start."
      exit 1
    fi
  done
}

# Kill all parallel processes below
trap "kill 0" SIGINT

caddy run --config /etc/caddy/Caddyfile --adapter caddyfile \
& spacetime start --listen-addr 0.0.0.0:3000 --data-dir /stdb \
& deploy \
&& wait